apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-demo
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-demo
  template:
    metadata:
      labels:
        app: storage-demo
    spec:
      containers:
        - name: storage-demo
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-storage
              mountPath: /usr/share/nginx/html/data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
